# Install: `brew bundle --file base.Brewfile`.

# Taps.
tap "homebrew/bundle"
tap "koekeishiya/formulae"

# Binaries.
# brew "awscli"
# brew "azcopy"
# brew "azure-cli"
# brew "btop"  # Resource monitoring.
# brew "cloud-sql-proxy"
# brew "duckdb"
# brew "git-lfs"
# brew "gnupg"
# brew "go"
# brew "hadolint"
# brew "helm"
# brew "jq"
# brew "kubernetes-cli"
# brew "libpq"
# brew "MonitorControl"
# brew "postgresql"
brew "bat"
brew "bottom"
brew "broot" # Terminal file explorer.
brew "colima", restart_service: true
brew "deno" # JS and TS runtime.
# Still required with colima.
brew "docker-buildx"
brew "docker-compose"
brew "docker"
brew "eva" # Calculator.
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-quick-stats"
brew "htop"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "mackup"
brew "mas"
brew "neovim"
brew "nvm"
brew "ollama"
brew "parallel"
brew "pyenv"
brew "ripgrep" # Faster grep.
brew "rm-improved"
brew "rust"
brew "shellcheck"
brew "starship"
brew "terraform"
brew "the_silver_searcher" # ag.
brew "tldr"
brew "tmux"
brew "tokei" # Stats about code.
brew "watch"
brew "wget"
brew "yank"
brew "zoxide"

# Applications.
# cask "cursor"
# cask "discord"
# cask "gimp"
# cask "google-backup-and-sync"
# cask "google-chrome"
# cask "google-cloud-sdk"
# cask "julia"
# cask "keybase"
# cask "libreoffice"
# cask "lm-studio"
# cask "microsoft-teams"
# cask "monitorcontrol"
# cask "ngrok"
# cask "shortcat"
# cask "temurin"
# cask "webtorrent"
# cask "znotch"
cask "alacritty"
cask "arduino-ide"
cask "chatgpt"
cask "cyberduck"
cask "dbeaver-community"
cask "deskpad"
cask "electrum"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "hammerspoon"
cask "hiddenbar"
cask "karabiner-elements"
cask "keepassxc"
cask "lulu"
cask "maccy"
cask "onyx"
cask "postman"
cask "sloth"
cask "superhuman"
cask "the-unarchiver"
cask "tor-browser"
cask "transmission"
cask "utm"
cask "visual-studio-code" # vscodium
cask "vlc"
cask "wireshark"

# Mac App Store applications.
mas "Amphetamine", id: 937984704
mas "Next Meeting", id: 1017470484
mas "NordVPN: VPN Fast & Secure", id: 905953485

# VSCode extensions.
# vscode "github.vscode-pull-request-github"
# vscode "golang.go"
# vscode "ivan-bocharov.stan-vscode"
# vscode "lokalise.i18n-ally"
# vscode "ms-azuretools.vscode-azureresourcegroups"
# vscode "ms-azuretools.vscode-bicep"
# vscode "ms-dotnettools.vscode-dotnet-runtime"
# vscode "ms-vscode-remote.remote-containers"
# vscode "ms-vscode.azure-account"
# vscode "mtxr.sqltools-driver-pg"
# vscode "mtxr.sqltools"
# vscode "orta.vscode-jest"
# vscode "redhat.java"
# vscode "rust-lang.rust-analyzer"
# vscode "sonarsource.sonarlint-vscode"
# vscode "vadimcn.vscode-lldb"
# vscode "vscjava.vscode-gradle"
# vscode "vscjava.vscode-java-debug"
# vscode "vscjava.vscode-java-dependency"
# vscode "vscjava.vscode-java-pack"
# vscode "vscjava.vscode-java-test"
# vscode "vscjava.vscode-maven"
# vscode "yinfei.luahelper"
vscode "adpyke.vscode-sql-formatter"
vscode "bierner.markdown-mermaid"
vscode "charliermarsh.ruff"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "foxundermoon.shell-format"
vscode "github.copilot-chat"
vscode "github.copilot"
vscode "hashicorp.terraform"
vscode "mechatroner.rainbow-csv"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "naumovs.color-highlight"
vscode "njpwerner.autodocstring"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "usernamehw.errorlens"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "wayou.vscode-todo-highlight"
vscode "yzane.markdown-pdf"
vscode "zhuangtongfa.material-theme"
