# Install: `brew bundle --file base.Brewfile`.

# Taps.
tap "koekeishiya/formulae"

# Binaries.
# brew "awscli"
# brew "azcopy"
# brew "azure-cli"
# brew "cloud-sql-proxy"
# brew "duckdb"
# brew "hadolint"
# brew "helm"
# brew "kubernetes-cli"
# brew "libpq"
# brew "presenterm"
# brew "terraform"
brew "agent-browser" # Browser automation CLI for AI agents.
brew "bat"
brew "bottom"
brew "colima", restart_service: true
brew "deno" # JS and TS runtime.
brew "docker"
brew "docker-buildx" # Still required with colima.
brew "docker-compose" # Still required with colima.
brew "eva" # Calculator.
brew "eza"
brew "fd"
brew "fzf"
brew "gh" # GitHub CLI.
brew "git-delta"
brew "git-lfs"
brew "git-quick-stats"
brew "go"
brew "htop"
brew "infat"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "lazygit"
brew "mackup"
brew "mas"
brew "neovim"
brew "nvm"
brew "ollama"
brew "parallel"
brew "ripgrep" # Faster grep.
brew "rust"
brew "shellcheck"
brew "starship"
brew "terminal-notifier"
brew "tldr"
brew "tmux"
brew "tokei" # Stats about code.
brew "uv"
brew "watch"
brew "wget"
brew "yank"
brew "yazi" # Terminal file manager.
brew "zoxide"

# Applications.
# cask "cyberduck"
# cask "discord"
# cask "gimp"
# cask "google-cloud-sdk"
# cask "inkscape"
# cask "kid3" # Audio tag editor.
# cask "libreoffice"
# cask "ngrok"
# cask "nuclear"
# cask "openmtp"
# cask "shortcat"
# cask "tor-browser"
# cask "tunnelblick"
# cask "wireshark"
cask "alacritty"
cask "arduino-ide"
cask "bruno"
cask "chromium"
cask "claude-code"
cask "codex"
cask "conductor"
cask "dbeaver-community"
cask "electrum"
cask "font-jetbrains-mono-nerd-font"
cask "google-drive"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "keepassxc"
cask "lulu"
cask "maccy"
cask "meetingbar"
cask "nordvpn"
cask "onyx"
cask "sloth"
cask "tailscale-app"
cask "the-unarchiver"
cask "transmission"
cask "utm"
cask "visual-studio-code" # vscodium
cask "vlc"
cask "zen"

# Mac App Store applications.
mas "Amphetamine", id: 937984704

# VSCode extensions.
# vscode "ms-vscode-remote.remote-containers"
# vscode "orta.vscode-jest"
# vscode "vadimcn.vscode-lldb"
vscode "adpyke.vscode-sql-formatter"
vscode "bierner.markdown-mermaid"
vscode "charliermarsh.ruff"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "naumovs.color-highlight"
vscode "njpwerner.autodocstring"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "usernamehw.errorlens"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "wayou.vscode-todo-highlight"
vscode "yzane.markdown-pdf"
vscode "zhuangtongfa.material-theme"
