-- Import modules.
require('settings/general')
require("settings/editing")
require("settings/folding")
require("settings/search")
require("settings/ui")
require("plugins/init")
require("plugins/nerdcommenter")
require("plugins/nvim-treesitter")
require("plugins/onedark")
require("plugins/wilder")
require("keymappings/init")
