-- Import modules.
require("settings.general")
require("settings.editing")
require("settings.search")
require("settings.ui")
require("plugins.init")
require("plugins.nvim-treesitter")
require("plugins.onedark")
require("plugins.lsp")
require("plugins.telescope")
require("keymappings.init")
