# infat --config ~/.config/infat/config.toml

[extensions]
Brewfile = "Visual Studio Code"
conf  = "Visual Studio Code"
Dockerfile = "Visual Studio Code"
ini   = "Visual Studio Code"
js    = "Visual Studio Code"
json  = "Visual Studio Code"
jsx   = "Visual Studio Code"
md    = "Visual Studio Code"
py    = "Visual Studio Code"
rs    = "Visual Studio Code"
sh    = "Visual Studio Code"
svg   = "Zen"
toml  = "Visual Studio Code"
ts    = "Visual Studio Code"
tsx   = "Visual Studio Code"
txt   = "Visual Studio Code"
yaml  = "Visual Studio Code"

[schemes]
mailto = "Zen"
web    = "Zen"

[types]
makefile   = "Visual Studio Code"
plain-text = "Visual Studio Code"
shell      = "Visual Studio Code"
sourcecode = "Visual Studio Code"
